pipeline {
    agent any
    tools {
        maven 'Maven 3.8.6'
    }
    stages {
        stage('build') {
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                dir('worker') {
                    echo 'Running unit test on worker app'
                    sh 'mvn clean test'
                }
            }
        }
        stage("package") {
            steps {
                dir('worker') {
                    echo 'Packaging worker app'
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline for worker app has finished.'
        }
        success {
            echo 'Pipeline was successful.'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
